import Head from "next/head";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import Carousel from "react-material-ui-carousel";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Slider from "react-slick";
import AspectRatio from "@mui/joy/AspectRatio";
import { Button, Card, Container, Grid, Link } from "@mui/material";
import Typography from "@mui/joy/Typography";
import CardContent from "@mui/joy/CardContent";

const inter = Inter({ subsets: ["latin"] });

var items = [
  {
    image:
      "https://images.pexels.com/photos/990432/pexels-photo-990432.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    image:
      "https://images.pexels.com/photos/6806609/pexels-photo-6806609.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    image:
      "https://images.pexels.com/photos/1666320/pexels-photo-1666320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    image:
      "https://images.pexels.com/photos/1130980/pexels-photo-1130980.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    image:
      "https://images.pexels.com/photos/19900720/pexels-photo-19900720/free-photo-of-reading-book.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
];

const settings = {
  dots: true,
  infinite: true,
  speed: 700,
  slidesToShow: 3,
  slidesToScroll: 1,
  autoplay: true,
};

export default function Home() {
  return (
    <>
      <Head>
        <title>BookOholic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={` ${inter.className}`}>
        <Container sx={{ display: "flex", justifyContent: "center" }}>
          <div>
            <Typography sx={{ fontSize: "30px", paddingTop:"80px", color:"white" }} level="h1">
              Read Your Favorite Books Online
            </Typography>
          </div>
        </Container>
        <Container
          sx={{
            display: "flex",
            justifyContent: "center",
            marginBottom: "20px",
          }}
        >
          <Button
            sx={{
              marginTop: "40px",
              fontSize: "20px",
              cursor: "pointer",
              marginRight: "20px",
              color: "lightgrey",
              "&:hover": {
                textDecoration: "underline",
                fontSize: "21px",
                color: "white",
              },
            }}
            href="/auth/login"
          >
            Log in and start reading!
          </Button>
          <Button
            sx={{
              marginTop: "40px",
              fontSize: "20px",
              cursor: "pointer",
              marginLeft: "20px",
              color: "lightgrey",
              "&:hover": {
                textDecoration: "underline",
                fontSize: "21px",
                color: "white",
              },
            }}
            href="/auth/register"
          >
            Don't have an Account? Sign Up!
          </Button>
        </Container>

        <Carousel sx={{ marginTop: "2rem", marginBottom: "2rem" }}>
          {items.map((item) => (
            <AspectRatio maxHeight="720px">
              <img src={item.image} />
            </AspectRatio>
          ))}
        </Carousel>

        <Container sx={{ marginBottom: "20px" }}>
          <Grid container columns={12} sx={{ paddingTop: "70px" }}>
            <Grid item xs={4}>
              <Card sx={{ width: 310, backgroundColor: "#697565",
                    ":hover": {
                      boxShadow: 18,
                    }, }}>
                <AspectRatio minHeight="430px" maxHeight="500px">
                  <img
                    src="https://m.media-amazon.com/images/I/51v00EQEFlL._SY445_SX342_.jpg"
                    alt=""
                  />
                </AspectRatio>

                <CardContent orientation="horizontal" sx={{ padding: "10px 20px" }}>
                  <div>
                    <Typography
                      sx={{ color: "white", margin: "1px", fontSize: "16px" }}
                      level="title-lg"
                    >
                      Powerless <br /> LAUREN ROBERTS
                    </Typography>
                    
                    <Typography sx={{ color: "white" }} level="body-xs">
                      Total price:
                    </Typography>

                    <Typography
                      sx={{ color: "white" }}
                      fontSize="lg"
                      fontWeight="lg"
                    >
                      ₹340
                    </Typography>
                  </div>
                  <Button
                    variant="solid"
                    size="md"
                    sx={{
                      ml: "auto",
                      alignSelf: "center",
                      fontWeight: 600,
                      color: "white",
                      backgroundColor: "#7ABA78",
                    }}
                  >
                    Buy Now!
                  </Button>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={4}>
              <Card sx={{ width: 310, backgroundColor: "#697565",
                    ":hover": {
                      boxShadow: 18,
                    }, }}>
                <AspectRatio minHeight="430px" maxHeight="500px">
                  <img
                    src="https://m.media-amazon.com/images/I/41aGtZvMlRL._SY780_.jpg"
                    alt=""
                  />
                </AspectRatio>

                <CardContent orientation="horizontal" sx={{ padding: "10px 20px" }}>
                  <div>
                    <Typography
                      sx={{ color: "white", margin: "1px", fontSize: "15px" }}
                      level="title-lg"
                    >
                      The Housemaid is Watching <br /> FREIDA McFADDEN
                    </Typography>

                    <Typography
                      sx={{ color: "white" }}
                      fontSize="lg"
                      fontWeight="lg"
                    >
                      ₹470
                    </Typography>
                  </div>
                  <Button
                    variant="solid"
                    size="md"
                    sx={{
                      width:"115px",
                      ml: "auto",
                      alignSelf: "center",
                      fontWeight: 600,
                      color: "white",
                      backgroundColor: "#7ABA78",
                    }}
                  >
                    Buy Now!
                  </Button>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={4}>
              <Card sx={{ width: 310, backgroundColor: "#697565",
                    ":hover": {
                      boxShadow: 18,
                    }, }}>
                <AspectRatio minHeight="430px" maxHeight="500px">
                  <img
                    src="https://m.media-amazon.com/images/I/71Zm6Ycg5QL._SY466_.jpg"
                    alt=""
                  />
                </AspectRatio>

                <CardContent orientation="horizontal" sx={{ padding: "10px 20px" }}>
                  <div>
                    <Typography
                      sx={{ color: "white", margin: "1px", fontSize: "16px" }}
                      level="title-lg"
                    >
                      Can You Find Me? <br />- HIMANSHI JAIN
                    </Typography>

                    <Typography sx={{ color: "white" }} level="body-xs">
                      Total price:
                    </Typography>
                    <Typography
                      sx={{ color: "white" }}
                      fontSize="lg"
                      fontWeight="lg"
                    >
                      ₹800
                    </Typography>
                  </div>
                  <Button
                    variant="solid"
                    size="md"
                    sx={{
                      ml: "auto",
                      alignSelf: "center",
                      fontWeight: 600,
                      color: "white",
                      backgroundColor: "#7ABA78",
                    }}
                  >
                    Buy Now!
                  </Button>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </Container>

        <Container>
          <Grid
            container
            columns={12}
            sx={{ paddingTop: "70px", marginBottom: "120px" }}
          >
            <Grid item xs={3}>
              <div>
                <img
                  src="https://m.media-amazon.com/images/I/6172isZX4UL._AC_UF1000,1000_QL80_.jpg"
                  height={450}
                  width="auto"
                />
              </div>
            </Grid>
            <Grid item xs={9}>
              <div
                style={{
                  marginTop: "18px",
                  marginLeft: "60px",
                  color: "#ECDFCC",
                  fontFamily: "serif",
                  fontWeight: "lighter",
                }}
              >
                <h5
                  style={{
                    fontSize: "25px",
                    color: "#ECDFCC",
                    marginBottom: "12px",
                  }}
                >
                  How To Kill Your Family - BELLA MAKIE
                </h5>
                <p
                  style={{
                    fontSize: "22px",
                  }}
                >
                  {" "}
                  <i>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Pellentesque arcu augue, dignissim non velit sit amet,
                    ultricies faucibus tellus. Nam rhoncus, enim in mattis
                    malesuada, lectus massa fermentum dolor, et aliquam dui
                    lacus et mi. Ut hendrerit enim nec lacus tempus, at maximus
                    mi sollicitudin. Cras sit amet iaculis ante. Vestibulum quis
                    ex at tellus tristique aliquet. <br />
                    Duis tristique nibh sit amet sagittis ullamcorper. Cras
                    vulputate vehicula dolor, convallis finibus ipsum. Nam vel
                    velit risus. Maecenas eros eros, porttitor ut tincidunt vel,
                    dignissim eget dolor. Vestibulum tristique sit amet elit id
                    gravida. Suspendisse maximus ultricies lorem, id euismod
                    enim elementum nec.
                  </i>
                </p>
                <Button
                  sx={{
                    color: "white",
                    backgroundColor: "#7ABA78",
                    marginTop: "12px",
                    padding: "8px 20px",
                    ":hover": { scale: "1.2" },
                  }}
                >
                  Buy Now
                </Button>
              </div>
            </Grid>
          </Grid>
        </Container>

        <Container>
          <Grid
            container
            columns={12}
            sx={{ paddingTop: "70px", marginBottom: "120px" }}
          >
            <Grid item xs={9}>
              <div
                style={{
                  marginTop: "18px",
                  marginRight: "60px",
                  color: "#ECDFCC",
                  fontFamily: "serif",
                  fontWeight: "lighter",
                }}
              >
                <h5
                  style={{
                    fontSize: "25px",
                    color: "#ECDFCC",
                    marginBottom: "12px",
                  }}
                >
                  Twisted Series - ANA HUANG
                </h5>
                <p
                  style={{
                    fontSize: "22px",
                  }}
                >
                  {" "}
                  <i>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Pellentesque arcu augue, dignissim non velit sit amet,
                    ultricies faucibus tellus. Nam rhoncus, enim in mattis
                    malesuada, lectus massa fermentum dolor, et aliquam dui
                    lacus et mi. Ut hendrerit enim nec lacus tempus, at maximus
                    mi sollicitudin. Cras sit amet iaculis ante. Vestibulum quis
                    ex at tellus tristique aliquet. <br />
                    Duis tristique nibh sit amet sagittis ullamcorper. Cras
                    vulputate vehicula dolor, convallis finibus ipsum. Nam vel
                    velit risus. Maecenas eros eros, porttitor ut tincidunt vel,
                    dignissim eget dolor. Vestibulum tristique sit amet elit id
                    gravida. Suspendisse maximus ultricies lorem, id euismod
                    enim elementum nec.
                  </i>
                </p>
                <Button
                  sx={{
                    color: "white",
                    backgroundColor: "#7ABA78",
                    marginTop: "12px",
                    padding: "8px 20px",
                    ":hover": { scale: "1.2" },
                  }}
                >
                  Buy Now
                </Button>
              </div>
            </Grid>
            <Grid item xs={3}>
              <div>
                <img
                  src="https://readerinbookland.in/wp-content/uploads/2023/03/Screenshot_20230304-163355-773-e1678822729341-1.jpg"
                  height={450}
                  width="auto"
                />
              </div>
            </Grid>
          </Grid>
        </Container>

        <Container>
          <div style={{ margin: "60px" }}>
            <Slider {...settings}>
              <img
                id="k"
                src="https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg"
                alt=""
                height="500px"
              />

              <img
                id="k"
                src="https://m.media-amazon.com/images/I/51ulQuaRoqL._AC_UF1000,1000_QL80_.jpg"
                alt=""
                height="500px"
              />

              <img
                id="k"
                src="https://m.media-amazon.com/images/I/81bGf1ytXqL._AC_UF1000,1000_QL80_.jpg"
                alt=""
                height="500px"
              />

              <img
                id="k"
                src="https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1671336608i/62047984.jpg"
                alt=""
                height="500px"
              />

              <img
                id="k"
                src="https://m.media-amazon.com/images/I/41jn8bGp1oL._SY445_SX342_.jpg"
                alt=""
                height="500px"
              />

              <img
                id="k"
                src="https://m.media-amazon.com/images/I/51T5p4t9YuL._SY445_SX342_.jpg"
                alt=""
                height="500px"
              />
            </Slider>
          </div>
        </Container>

        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  );
}
